export const projects = [
  { id: 1, name: "Task Management", category: "Laravel", describe: "This project is a task management site built by React.js, Laravel 8.1.5, Tailwindcss, React-Bootstrap.", link: "https://github.com/anupammallick88/Task-Management", tag: 'Laravel, React.Js, javaScript, Tailwindcss' },
  { id: 2, name: "E-commerce Agro", category: "Angular", describe: "eCommerce-Agro is a ecommerce project, where innovation meets functionality across four major modules: Admin, Web, Store, and User. A full stack e-commerce project with Angular, firebase, Codeigniter and MySQL.", link: "https://github.com/anupammallick88/E-commerce-Agro-Project", tag: 'Angular, Firebase, Codeigniter, MySql, Bootstrap, Jwt, RxJs' },
  { id: 3, name: "Small Scale eCommerce", category: "Angular", describe: "Welcome to our small-scale eCommerce project, where innovation meets convenience! With the perfect blend of cutting-edge frontend technology using Angular and robust backend support through Laravel, we've crafted a seamless online shopping experience that caters to your every need.", link: "https://github.com/anupammallick88/Small-Scale-eCommerce", tag: 'Laravel, Angular, TypeScript, Restful-api, Bootstrap, RxJs' },
  { id: 4, name: "eCommerce Backend", category: "Laravel", describe: "Small-scale eCommerce project, where innovation meets convenience! With the perfect blend of cutting-edge frontend technology using Angular and robust backend support through Laravel.", link: "https://github.com/anupammallick88/Small-Scale-eCommerce", tag: 'laravel, vue.js, javaScript, Laravel-Passport' },
  { id: 5, name: "CarRental Frontend", category: "Angular", describe: "Car Rental Frontend Project Using Angular, material, rxjs.", link: "https://github.com/anupammallick88/CarRental-Project-FrontEnd", tag: 'Angular, Material ui, rxjs' },
  { id: 6, name: "Restaurant Management System", category: "Angular", describe: "This project was generated with Angular CLI version 16.1.8. This is a Machine test interview project. It's frist develop on angular version 12.2.10. Now I update the Angular version 16.1.8.", link: "https://github.com/anupammallick88/Restaurent_Application", tag: 'Angular, rxjs, Tailwindcss' },
  { id: 7, name: "Telemedicine System", category: "Laravel", describe: "An One Telemedicine system is a technological solution designed to monitor and manage the health and well-being of patients from a distance.", link: "https://github.com/anupammallick88/OneTelemedicine", tag: 'Laravel, javascript, mysql, Bootstrap, vue.js, blade-template, php-jwt' },
  { id: 8, name: "Accounting-System(POS)", category: "Laravel", describe: "A Point of Sale (POS) system is a commonly found in retail stores, restaurants, and various other businesses that sell products or services directly to customers.", link: "https://github.com/anupammallick88/Accounting-System-POS", tag: 'Laravel, mysql, blade-template, laravel-passport, twillio, paypal' },
  { id: 9, name: "My portfolio", category: "React", describe: "This is my personal portfolio website using React-18.2.0, bootstrap, react-bootstrap, framer-motion, react-slick, and slick-carousel.", link: "https://github.com/anupammallick88/My portfolio", tag: 'React, bootstrap, react-bootstrap, framer-motion, react-slick, and slick-carousel' },
  
    // Add more products
  ];